version: '3.8'

services:
  api:
    build: .
    ports:
      - "8081:8081"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`pvmg10.sae.powervision.me`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=8081"

  traefik:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080" # Optional: Traefik dashboard
    command:
      - "--api.insecure=true" # Enable Traefik dashboard (optional)
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
